### ISSUE TITLE
suggestion: remove question mark on redirect

### ISSUE THREAD

**Issue by steveoh** [tmcw/linkrot#3]
This was a little confusing to me because `?` is a valid url component but in the case of the cli it is treating it as proper punctuation...

`✔ redirect https://gis.utah.gov/data to https://gis.utah.gov/data/?`

The `?` makes it a little bit harder to notice that this is only a trailing slash modification.

**Comment by tmcw** [comment]
Totally, you're right. Happy to accept a PR or I'll make this change later today

**Comment by steveoh** [comment]
Great, i'll submit that in a second.
