### ISSUE TITLE
suggestion: context with colors

### ISSUE THREAD

**Issue by steveoh** [tmcw/linkrot#4]
I think it would make things a little simpler and quicker to decide whether to update or not if the two links were color coded in the cli.

In a small terminal window when things wrap it is hard to pick out the ` to ` to see where one link starts and the other ends.

I suppose this could be as simple as adding chalk.

**Comment by steveoh** [comment]
If colors are not wanted, maybe some line feeds or some other formatting could help?

**Comment by tmcw** [comment]
Thanks for the idea! The future of linkrot is all about github actions rather than the cli, because it provides a better way to do this kind of thing continuous and can automatically open PRs. So special formatting, definitely, but it'll be in PR descriptions.
